export const jsonOrgan = [
  {
    id: 15,
    cargo: "Presidente",
    nome: "Yuri Câmara",
    idcargo: 1,
    departamentos: [
      {
        id: 2,
        cargo: "SEGOV",
        nome: "Bruno Capadosia",
        idcargo: 7,
        divisões: [
          {
            id: 71,
            cargo: "Desenv Proj Fer Australia",
            nome: "Morina Yoda",
            idcargo: 70,
            pai: 7,
          },
          {
            id: 72,
            cargo: "Projetos China",
            nome: "Antonio Gablad",
            idcargo: 71,
            pai: 7,
          },
        ],
        drop: false,
      },
      {
        id: 3,
        cargo: "Gerente de Implantações",
        nome: "Carlos Padeiro",
        idcargo: 6,
        divisões: [
          {
            id: 60,
            cargo: "Supr. Estrat. Serviços e VLI",
            nome: "Mariano da Silva",
            idcargo: 54,
            pai: 6,
          },
          {
            id: 53,
            cargo: "Suprim Est Americas Proj Ferrosos e Log",
            nome: "Natassya Câmara",
            idcargo: 47,
            pai: 6,
          },
          {
            id: 54,
            cargo: "Grandes Contratos de Obras Civis",
            nome: "Izabel Fernandes",
            idcargo: 48,
            pai: 6,
          },
          {
            id: 55,
            cargo: "Suprimentos de Equip. e Sistemas",
            nome: "Papito Aquino",
            idcargo: 49,
            pai: 6,
          },
          {
            id: 56,
            cargo: "Supr. Estrat. Europa, OM e Africa",
            nome: "Luana Davilla",
            idcargo: 50,
            pai: 6,
          },
          {
            id: 58,
            cargo: "Suprimentos Projetos Asia/Pacifico",
            nome: "Marco Bonilha",
            idcargo: 52,
            pai: 6,
          },
          {
            id: 59,
            cargo: "Supr. Estrat. Siderurgia, Energia",
            nome: "Tamara Rasata",
            idcargo: 53,
            pai: 6,
          },
          {
            id: 57,
            cargo: "Supr. Estrat. Americas",
            nome: "Rafael Mulio",
            idcargo: 51,
            pai: 6,
          },
        ],
        drop: false,
      },
      {
        id: 4,
        cargo: "Gerente de Operação",
        nome: "Carla Monicota",
        idcargo: 5,
        divisões: [
          {
            id: 44,
            cargo: "Inteligência e Desenv.",
            nome: "Daniel Mamosa",
            idcargo: 31,
            pai: 5,
          },
          {
            id: 45,
            cargo: "Suprimentos Planej e Qualidade",
            nome: "Efanasio Aleluia",
            idcargo: 34,
            pai: 5,
          },
          {
            id: 46,
            cargo: "Planning Control",
            nome: "Gatuso Armelio",
            idcargo: 35,
            pai: 5,
          },
          {
            id: 26,
            cargo: "Suprimentos EMEA",
            nome: "Helio Apogrado",
            idcargo: 11,
            pai: 5,
          },
          {
            id: 22,
            cargo: "Suprimentos América do Sul",
            nome: "Juliano Herdeiro",
            idcargo: 8,
            pai: 5,
          },
          {
            id: 28,
            cargo: "Suprimentos Ásia",
            nome: "Gustavo Nascimento",
            idcargo: 13,
            pai: 5,
          },
          {
            id: 23,
            cargo: "Supr.Est.Bra/Amer",
            nome: "Rodolfo do Sol",
            idcargo: 9,
            pai: 5,
          },
          {
            id: 27,
            cargo: "Suprimentos América do Norte",
            nome: "Marcos Fusco",
            idcargo: 12,
            pai: 5,
          },
          {
            id: 25,
            cargo: "Supr.Est.Bra/Amer",
            nome: "Marcelo Padeco",
            idcargo: 10,
            pai: 5,
          },
        ],
        drop: false,
      },
    ],
  },
];
